# Site settings
title: Manchester Fire Support Group 
email: bod@mfsgct.org
joinemail: join@mfsgct.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mfsgct.org" # the base hostname & protocol for your site

collections:
  events:

# Build settings
markdown: kramdown
